/**
 * Global Constants & Canonical DOM Selectors for Gemini UI
 */

export const KNOWN_LANGUAGES: ReadonlySet<string> = new Set([
    "python",
    "py",
    "python3",
    "py3",
    "javascript",
    "js",
    "jsx",
    "mjs",
    "cjs",
    "typescript",
    "ts",
    "tsx",
    "mts",
    "cts",
    "c",
    "cpp",
    "c++",
    "cc",
    "cxx",
    "h",
    "hpp",
    "csharp",
    "c#",
    "cs",
    "java",
    "rust",
    "rs",
    "go",
    "golang",
    "ruby",
    "rb",
    "php",
    "swift",
    "kotlin",
    "kt",
    "scala",
    "html",
    "htm",
    "css",
    "scss",
    "sass",
    "less",
    "sql",
    "mysql",
    "pgsql",
    "postgres",
    "plsql",
    "sqlite",
    "bash",
    "shell",
    "sh",
    "zsh",
    "fish",
    "powershell",
    "ps1",
    "batch",
    "bat",
    "cmd",
    "json",
    "json5",
    "jsonc",
    "yaml",
    "yml",
    "toml",
    "xml",
    "svg",
    "markdown",
    "md",
    "latex",
    "tex",
    "graphql",
    "gql",
    "dockerfile",
    "docker",
    "makefile",
    "make",
    "cmake",
    "r",
    "julia",
    "jl",
    "lua",
    "perl",
    "pl",
    "haskell",
    "hs",
    "elixir",
    "ex",
    "erlang",
    "erl",
    "dart",
    "assembly",
    "asm",
    "wasm",
    "diff",
    "patch",
    "vim",
    "viml",
    "ini",
    "env",
    "proto",
    "protobuf",
]);

// Canonical DOM selectors for Gemini UI
export const SELECTOR_ROOT = ".response-element code-block, response-element code-block, code-block";
export const SELECTOR_DECORATION = ".code-block-decoration, .code-block-decoration-header, header";
export const SELECTOR_LANG_SPAN = ".code-block-decoration-title, .language-label, :scope > span";
export const SELECTOR_CODE_CONTAINER = 'code.code-container[data-test-id="code-content"], code, pre';
export const SELECTOR_ACTIONS = ".buttons, .code-block-decoration-actions, .header-actions";
export const SELECTOR_NOT_PROCESSED = ":not([data-code-processed])";
